product: ucs
release: "5.0"
version: [1]
scope: ucs_5.0-0-errata5.0-1
src: univention-management-console-adtakeover
fix: 
desc: |
 This update addresses the following issue:
    * The operative system call with subprocess in python takeover.py to systemctl try-start don't use the full directory path
bug: [54238]
